[project]
name = "weixiaotien"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.79.0",
    "py-markdown-table>=1.3.0",
    "pydantic>=2.11.4"
]
